#!/bin/sh
# One-time preparation of the server after cloning the repository.
# Run from the repository root as a regular user with sudo rights: ./server_setup.sh
# (not as root, it updates git metadata of the repository).
# Asks interactively for secrets. Existing values are never overwritten, so it is safe to re-run.
set -eu

cd "$(dirname "$0")"

# Container user of Zabbix images
ZBX_UID=1997
ZBX_GID=1995

# Read value without echo to terminal
read_secret() {
    printf '%s' "$1" >&2
    stty -echo
    trap 'stty echo' EXIT INT TERM
    IFS= read -r secret_value || secret_value=""
    stty echo
    trap - EXIT INT TERM
    printf '\n' >&2
    printf '%s' "$secret_value"
}

# Ask secret twice, empty input means "generate random value"
ask_secret() {
    while :; do
        first=$(read_secret "$1 (empty = generate random): ")
        [ -z "$first" ] && return 0
        second=$(read_secret "Repeat: ")
        if [ "$first" = "$second" ]; then
            printf '%s' "$first"
            return 0
        fi
        echo "Values do not match, try again." >&2
    done
}

# Host directories used by compose_server.yaml
mkdir -p ./zabbix_agentd.d ./zabbix-db-data ./alertscripts ./externalscripts \
    ./letsencrypt/webroot ./backups ./snmptraps

# Keep local data and secrets out of git without changing tracked .gitignore
for p in /zabbix-db-data/ /server.env /letsencrypt/ /backups/ /snmptraps/snmptrapd.conf; do
    grep -qxF "$p" .git/info/exclude 2>/dev/null || echo "$p" >> .git/info/exclude
done

[ -e server.env ] || cp server.env.example server.env

# PostgreSQL password. It is applied only when database is initialized (empty ./zabbix-db-data).
if [ "$(cat env_vars/.POSTGRES_PASSWORD)" = "zabbix" ]; then
    if [ -n "$(ls -A ./zabbix-db-data 2>/dev/null)" ]; then
        echo "WARNING: ./zabbix-db-data is already initialized, PostgreSQL password is left unchanged." >&2
    else
        db_password=$(ask_secret "PostgreSQL password for Zabbix")
        [ -n "$db_password" ] || db_password=$(openssl rand -base64 24 | tr -d '\n')
        printf '%s' "$db_password" > env_vars/.POSTGRES_PASSWORD
        unset db_password
        # Keeps local password out of commits and "git pull" conflicts
        git update-index --skip-worktree env_vars/.POSTGRES_PASSWORD
        echo "Saved PostgreSQL password in env_vars/.POSTGRES_PASSWORD"
    fi
fi

# Let's Encrypt account contact e-mail (account recovery and policy notices).
# Let's Encrypt no longer sends expiry notices, expiry is monitored by Zabbix (docs/despliegue/instalacion.md).
if grep -q '^LETSENCRYPT_EMAIL=$' server.env; then
    while :; do
        printf "E-mail for Let's Encrypt account: " >&2
        IFS= read -r le_email
        case "$le_email" in
            *@*.*) break ;;
            *) echo "Invalid e-mail, try again." >&2 ;;
        esac
    done
    sed -i.bak "s|^LETSENCRYPT_EMAIL=.*|LETSENCRYPT_EMAIL=${le_email}|" server.env
    rm -f server.env.bak
fi

# SNMP trap community, stored only in snmptraps/snmptrapd.conf
if [ ! -e snmptraps/snmptrapd.conf ]; then
    while :; do
        community=$(ask_secret "SNMP trap community")
        if [ -z "$community" ]; then
            community=$(openssl rand -hex 12)
            echo "Generated SNMP trap community: ${community}"
            echo "Configure it on network devices, it is shown only now (stored in snmptraps/snmptrapd.conf)."
        fi
        case "$community" in
            *[!A-Za-z0-9._-]*) echo "Use only letters, digits, '.', '_' and '-'." >&2 ;;
            *) break ;;
        esac
    done

    umask 077
    cat > snmptraps/snmptrapd.conf <<EOF
# Generated by server_setup.sh, replaces /etc/snmp/snmptrapd.conf of zabbix-snmptraps image.
# Traps are accepted only with configured community (image default accepts any).
snmpTrapdAddr udp:1162
snmpTrapdAddr udp6:1162

# Do not fork from the calling shell
doNotFork yes

authCommunity log,execute,net ${community}
ignoreAuthFailure yes

traphandle default /bin/bash /usr/sbin/zabbix_trap_handler.sh
EOF
    umask 022
    unset community
    # snmptrapd runs as Zabbix container user
    sudo chown "${ZBX_UID}:${ZBX_GID}" snmptraps/snmptrapd.conf
fi

# Daily backup and certificate renewal, run as root (host cron configuration kept in the project)
if [ ! -e /etc/cron.d/zabbix ]; then
    sudo tee /etc/cron.d/zabbix > /dev/null <<EOF
# Zabbix backups and certificate renewal (times in host time zone), installed by server_setup.sh
30 2 * * * root $(pwd)/server_backup.sh >> /var/log/zabbix-backup.log 2>&1
0 4 * * * root $(pwd)/server_letsencrypt.sh renew >> /var/log/zabbix-letsencrypt.log 2>&1
EOF
    sudo chmod 644 /etc/cron.d/zabbix
    echo "Installed /etc/cron.d/zabbix"
fi

# lm-sensors on host: loads sensor drivers, agent 2 reads them from /sys/class/hwmon
# (zabbix_agentd.d/sensors_hwmon.conf)
if ! command -v sensors >/dev/null 2>&1; then
    printf 'Install lm-sensors for host temperature monitoring? [Y/n] ' >&2
    IFS= read -r answer
    case "$answer" in
        [nN]*) ;;
        *)
            if command -v apt-get >/dev/null 2>&1; then
                sudo apt-get update && sudo apt-get install -y lm-sensors
            elif command -v dnf >/dev/null 2>&1; then
                sudo dnf install -y lm_sensors
            elif command -v yum >/dev/null 2>&1; then
                sudo yum install -y lm_sensors
            else
                echo "WARNING: unknown package manager, install lm-sensors manually." >&2
            fi
            if command -v sensors-detect >/dev/null 2>&1; then
                # Detects chips and adds required kernel modules to be loaded on boot
                sudo sensors-detect --auto
                sudo systemctl enable --now lm-sensors 2>/dev/null \
                    || sudo systemctl enable --now lm_sensors 2>/dev/null || true
            fi
            ;;
    esac
fi
if command -v sensors >/dev/null 2>&1 && ! ls /sys/class/hwmon/hwmon*/temp*_input >/dev/null 2>&1; then
    echo "WARNING: no temperature sensors in /sys/class/hwmon (virtual machine or reboot required)." >&2
fi

echo
echo "Preparation finished. Next steps (see docs/despliegue/instalacion.md):"
echo "  docker compose --env-file .env --env-file server.env up -d"
echo "  sudo ./server_letsencrypt.sh issue"
